"""add phone number 2

Revision ID: 129a65e3866d
Revises: dd94796d9b8b
Create Date: 2022-09-26 18:07:08.147045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129a65e3866d'
down_revision = 'dd94796d9b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
